[profile.release]
debug = false
opt-level = 3
lto = true
codegen-units = 1

[workspace]
resolver = "2"
members = [
    "src"
]

[workspace.dependencies]
bnum = "*"
regex = "*"
ntest = "*"
lazy_static = "*"
timed = "*"
rand = "*"
fs = "*"
hotpath = "*"
toml = "*"

