[profile.release]
debug = false
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
debug = true

[workspace]
resolver = "2"
members = [
    "src"
]

[workspace.dependencies]
bnum = "*"
regex = "*"
ntest = "*"
lazy_static = "*"
timed = "*"
rayon = "*"
rand = "*"
fs = "*"
hotpath = "*"
backtrace-on-stack-overflow = "0.3.0"
