[workspace]
resolver = "2"
members = [
    "src/main",
    "src/game",
]

[workspace.dependencies]
game = { path = "src/game" }

bnum = "*"
regex = "*"
ntest = "*"
lazy_static = "*"
timed = "*"
rayon = "*"
