[profile.release]
debug = false
opt-level = 3
lto = true
codegen-units = 1

[workspace]
resolver = "2"
members = [
    "src/main",
    "src/game",
    "src/io"
]

[workspace.dependencies]
game = { path = "src/game" }
io = { path = "src/io" }

bnum = "*"
regex = "*"
ntest = "*"
lazy_static = "*"
timed = "*"
rayon = "*"
rand = "*"
fs = "*"
