[package]
name = "main"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "anekamacam"
path = "src/main.rs"

[dependencies]
game = { workspace = true }
io = { workspace = true }
hotpath = { workspace = true }

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
