title="Chess"
initial_position="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -"
files=8
ranks=8

[special_rules]
castling=true
en_passant=true
promotion=true
drop=false
count_limit=false
forbidden_zones=false

[[pieces]]
name="Pawn"
charset="Pp"
movement="mnW|im<nW-pnW>|tcnF"
value=1000
big=false
major=false
royal=false

[[pieces]]
name="Rook"
charset="Rr"
movement="R"
value=5000
big=true
major=true
royal=false

[[pieces]]
name="Knight"
charset="Nn"
movement="N"
value=3000
big=true
major=false
royal=false

[[pieces]]
name="Bishop"
charset="Bb"
movement="B"
value=3375
big=true
major=false
royal=false

[[pieces]]
name="Queen"
charset="Qq"
movement="Q"
value=3000
big=true
major=true
royal=false

[[pieces]]
name="King"
charset="K_"
movement="K|O{4}{2}|o{3}{1}"
value=inf
big=true
major=false
royal=true

[[pieces]]
name="King"
charset="_k"
movement="K|o{4}{2}|O{3}{1}"
value=inf
big=true
major=false
royal=true

[promotions]
P="RNBQ"
p="rbnq"

[promotion_zones_mandatory]
P="XXXXXXXX/8/8/8/8/8/8/8"
p="8/8/8/8/8/8/8/XXXXXXXX"

[initial_setup]
K="8/8/8/8/8/8/8/4X3"
k="4X3/8/8/8/8/8/8/8"
P="8/8/8/8/8/8/XXXXXXXX/8"
p="8/XXXXXXXX/8/8/8/8/8/8"
R="8/8/8/8/8/8/8/X6X"
r="X6X/8/8/8/8/8/8/8"
